---
- name: Install Jenkins Server on Local Machine
  hosts: localhost
  become: yes
  connection: local

  tasks:
    - name: Update APT and install Docker
      apt:
        update_cache: yes
        name: docker.io
        state: latest

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create Jenkins container
      command: docker run -d -p 8080:8080 --name jenkins_server jenkins/jenkins

    - name: Wait for Jenkins to initialize (optional but recommended)
      pause:
        seconds: 30

    - name: Get the Jenkins initial admin password
      command: docker exec jenkins_server cat /var/jenkins_home/secrets/initialAdminPassword
      register: jenkins_admin_password

    - name: Print the Jenkins initial admin password
      debug:
        msg: "The Jenkins initial admin password is: {{ jenkins_admin_password.stdout }}"