# playbook-install-jenkins-node.yml
---
- name: Install Jenkins Node
  hosts: jenkins_nodes
  become: yes

  tasks:
    - name: Update APT and install Docker
      apt:
        update_cache: yes
        name: docker.io
        state: latest

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Jenkins agent image
      docker_image:
        name: jenkins/inbound-agent
        source: pull

    - name: Create Jenkins node container
      docker_container:
        name: jenkins_agent
        image: jenkins/inbound-agent
        env:
          JENKINS_URL: "http://<jenkins_master_ip>:8080"
          JENKINS_SECRET: "<node_secret>"
          JENKINS_AGENT_NAME: "node-1"
        volumes:
          - /var/jenkins_agent:/var/jenkins_agent
        state: started
        restart_policy: always
