apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
  namespace: ps5
data:
  init.sql: |
    CREATE DATABASE auth;
    CREATE DATABASE event;
    CREATE DATABASE Test2_DB;
    CREATE DATABASE grpcmsg;

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: global-env-config
  namespace: ps5
data:
  POSTGRES_USER: root
  POSTGRES_PASSWORD: admin
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  AUTH_SERVICE: auth
  AUTH_PORT: "8088"
