apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: ps5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: azizdhoukar/ps5:Authentication-0.1
        ports:
        - containerPort: 8088
        env:
        - name: POSTGRES_USER
          value: root
        - name: POSTGRES_PASSWORD
          value: admin
        - name: POSTGRES_DB
          value: auth
        - name: POSTGRES_HOST
          value: postgres
        - name: POSTGRES_PORT
          value: "5432"

---
apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: ps5
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8088
      nodePort: 30001  
  type: NodePort
