apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: ps5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: azizdhoukar/ps5:Authentication-0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8088
        envFrom:
        - configMapRef:
            name: global-env-config

---
apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: ps5
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8088
      nodePort: 30008  
  type: NodePort
