apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: ps5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: azizdhoukar/ps5:Authentication
        ports:
        - containerPort: 8088

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: ps5
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8088
  type: LoadBalancer
