apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  namespace: ps5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
      - name: booking-service
        image: azizdhoukar/ps5:Booking
        #imagePullPolicy: Always
        ports:
        - containerPort: 8081
        envFrom:
        - configMapRef:
            name: global-env-config
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: ps5
spec:
  selector:
    app: booking-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
      nodePort: 30001  
  type: NodePort
