apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-management-service
  namespace: ps5
spec:
  replicas: 2
  selector:
    matchLabels:
      app: event-management-service
  template:
    metadata:
      labels:
        app: event-management-service
    spec:
      containers:
      - name: event-management-service
        image: your-registry/event-management-service:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: event-management-service
  namespace: ps5
spec:
  selector:
    app: event-management-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: ClusterIP
