apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-management-service
  namespace: ps5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-management-service
  template:
    metadata:
      labels:
        app: event-management-service
    spec:
      containers:
      - name: event-management-service
        image: azizdhoukar/ps5:EventManagement-0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8089
        envFrom:
        - configMapRef:
            name: global-env-config
---
apiVersion: v1
kind: Service
metadata:
  name: event-management-service
  namespace: ps5
spec:
  selector:
    app: event-management-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8089
      nodePort: 30009  
  type: NodePort
