apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-management-service
  namespace: ps5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-management-service
  template:
    metadata:
      labels:
        app: event-management-service
    spec:
      containers:
      - name: event-management-service
        image: azizdhoukar/ps5:EventManagement-0.1
        ports:
        - containerPort: 8089
        env:
        - name: POSTGRES_USER
          value: root
        - name: POSTGRES_PASSWORD
          value: admin
        - name: POSTGRES_HOST
          value: postgres
        - name: POSTGRES_PORT
          value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: event-management-service
  namespace: ps5
spec:
  selector:
    app: event-management-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8089
  type: ClusterIP
