apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: ps5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: azizdhoukar/ps5:Order
        #imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8083
        - name: grpc
          containerPort: 50050
        envFrom:
        - configMapRef:
            name: global-env-config
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: ps5
spec:
  selector:
    app: order-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8083
      nodePort: 30003
    - name: grpc
      protocol: TCP
      port: 50050
      targetPort: 50050
      nodePort: 30053
  type: NodePort
