---
- hosts: k8s-workers
  become: true
  tasks:
    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Enable and start Docker
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Install kubeadm, kubelet, and kubectl
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - kubeadm
        - kubelet
        - kubectl

    - name: Hold the Kubernetes packages at the current version
      apt:
        name:
          - kubeadm
          - kubelet
          - kubectl
        state: held

    - name: Join worker nodes to the cluster
      command: "{{ hostvars['k8s-master']['kubeadm_output']['stdout_lines'][0] }}"
      when: "'kubeadm join' in hostvars['k8s-master']['kubeadm_output']['stdout']"