apiversion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end   
    spec:
      containers:
      - name: nginx-container
        image: nginx
  replicas: 3
  selector:  # This is the selector that the ReplicaSet uses to determine which Pods to manage
    matchLabels:
      type: front-end  # This is the label that the ReplicaSet uses to match with the Pods it is supposed to manage
